### ISSUE TITLE
Redundant <div> inside <body>.

### ISSUE THREAD

**Issue by jaridnft** [vbertoletti/instanews#2]
Remove &lt;div class="page-cntr"&gt; and apply styles directly to &lt;body&gt;, the container is already in place.

**Comment by vbertoletti** [comment]
Please see below link for "Using the body tag vs. Using an additional div":
https://css-tricks.com/best-way-implement-wrapper-css/

**quote**
I would conclude it is still best practice to have an additional <div> for implementing a CSS wrapper. This way if spec requirements change later on you don't have to add the wrapper later and deal with moving the styles around. After all, we're only talking about one extra DOM element.
**unquote**
