### ISSUE TITLE
Repeated CSS - Delete Extra Variables

### ISSUE THREAD

**Issue by rcass** [vbertoletti/instanews#8]
Looks like you have these variables in both the variables partial and mixins partial.

Just remove the extra set from the mixins partial 👍 
https://github.com/vbertoletti/instanews/blob/c2c37fb587852e12626dcaaff3cb0b78b2cf4742/sass/partials/_mixins.scss#L1-L2

**Comment by vbertoletti** [comment]
thanks, removed.
