### ISSUE TITLE
Add 'overflow: hidden' to CSS

### ISSUE THREAD

**Issue by rcass** [vbertoletti/instanews#9]
I noticed on some stories that have longer text and if the window was less than desktop the words would overflow past its parent box, like this:
![screen shot 2018-08-07 at 10 25 51 am](https://user-images.githubusercontent.com/5028555/43792053-6baee68a-9a2c-11e8-8c7f-b65df70415f2.png)

Trying fiddling with 'overflow:hidden' in the CSS to stop this from happening.

**Comment by vbertoletti** [comment]
Thanks! It has been corrected.
